language: objective-c
osx_image: xcode7.1
before_install:
  - brew update
  - brew install carthage
script: xctool -project YTVimeoExtractor.xcodeproj -scheme YTVimeoExtractor test
before_deploy:
  - carthage build --no-skip-current
  - carthage archive YTVimeoExtractor
skip_cleanup: true
on:
  repo: repo/repo
  tags: true
